channels:
- conda-forge
dependencies:
- python=3.9.12
- pip<=21.2.4
- pip:
  - mlflow==2.10.2
  - cloudpickle==2.0.0
  - importlib-metadata==4.11.3
  - numpy==1.21.5
  - packaging==21.3
  - psutil==5.9.8
  - pyyaml==6.0
  - scikit-learn==1.0.2
  - scipy==1.7.3
name: mlflow-env
